# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
networks:
  lucas-net:
name: lucas

version: "3.9"
services:
  cassandra1:
    container_name: cassandra1
    hostname: cassandra1
    image: cassandra:4.1
    cpus: 2.0
    mem_limit: "3G"
    env_file:
      - cassandra.env
    volumes:
      - "./integration/cassandra/cassandra1.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 180
  
  cassandra2:
    container_name: cassandra2
    hostname: cassandra2
    image: cassandra:4.1
    cpus: 2.0
    mem_limit: "3G"
    env_file:
      - cassandra.env
    volumes:
      - "./integration/cassandra/cassandra2.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9044:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      cassandra1:
        condition: service_healthy
    
  cassandra3:
    container_name: cassandra3
    hostname: cassandra3
    image: cassandra:4.1
    cpus: 2.0
    mem_limit: "3G"
    env_file:
      - cassandra.env
    volumes:
      - "./integration/cassandra/cassandra3.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9045:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      cassandra2:
        condition: service_healthy
  
  cass_migrations:
    container_name: cass_migrations
    hostname: cass_migrations
    image: cass_migrations:latest
    build:
      context: .
      target: build
      dockerfile: Dockerfile_18
    entrypoint: ["bash", "/app/scripts/cass_migrations_entrypoint.sh"]
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_18:
    image: lucas18:latest
    container_name: lucas_18
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_18
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    depends_on:
      cassandra3:
        condition: service_healthy    

  driver_20:
    image: lucas20:latest
    container_name: lucas_20
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_20
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    depends_on:
      cassandra3:
        condition: service_healthy  

  driver_22:
    image: lucas22:latest
    container_name: lucas_22
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_22
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    depends_on:
      cassandra3:
        condition: service_healthy