# syntax=docker/dockerfile:1
FROM ubuntu:20.04 AS base

ENV LD_LIBRARY_PATH="/usr/local/lib/x86_64-linux-gnu"
ENV LUA_CPATH="/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so"
ENV LUA_PATH="/app/integration/tests/?.lua;;"
ARG DEBIAN_FRONTEND="noninteractive"
ARG CLANGD_TAG="15.0.6"
ARG STYLUA_TAG="v0.16.0"
ARG SHFMT_TAG="v3.6.0"
SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

COPY ./scripts/build-deps-* ./
RUN chmod +x ./build-deps-20.sh && ./build-deps-20.sh

COPY --from=mvdan/shfmt:v3-alpine /bin/shfmt /usr/bin/shfmt
# COPY --from=ghcr.io/JohnnyMorganz/StyLua:stylua:0.17.0 /stylua /usr/bin/stylua

COPY ./vendor /app/vendor/
WORKDIR /app/vendor/cpp-driver/build
RUN cmake .. && make -j`nproc` && make install
WORKDIR /app

FROM base AS build
COPY . /app/
RUN chmod +x ./scripts/build-w-cmake.sh && ./scripts/build-w-cmake.sh
WORKDIR /app
#RUN ./format.sh

FROM scratch AS artifacts
COPY --from=build /app/build/lucas.so* /
COPY --from=build /app/vendor/cpp-driver/build/libcassandra.so* /
