# syntax=docker/dockerfile:1
FROM alpine:3.17 AS base

LABEL maintainer="LotusFlare Persistence Infra <infra@lotusflare.com>"

ARG LD_LIBRARY_PATH
ARG LUA_CPATH
ENV LD_LIBRARY_PATH LD_LIBRARY_PATH
ENV LUA_CPATH LUA_CPATH

ENV LUA_PATH="/app/integration/tests/?.lua;;"
ARG CLANGD_TAG="15.0.6"
ARG STYLUA_TAG="v0.16.0"
ARG SHFMT_TAG="v3.6.0"

COPY ./scripts/build-deps-* ./
RUN chmod +x ./build-deps-alpine-317.sh && ./build-deps-alpine-317.sh

COPY --from=mvdan/shfmt:v3-alpine /bin/shfmt /usr/bin/shfmt
# COPY --from=ghcr.io/JohnnyMorganz/StyLua:stylua:0.17.0 /stylua /usr/bin/stylua

COPY ./vendor /app/vendor/
WORKDIR /app/vendor/cpp-driver/build
RUN cmake .. && make -j`nproc` && make install
WORKDIR /app

FROM base AS build
COPY . /app/
RUN chmod +x ./scripts/build-w-cmake.sh && ./scripts/build-w-cmake.sh
WORKDIR /app
#RUN ./format.sh

FROM scratch AS artifacts
COPY --from=build /app/build/lucas.so* /
COPY --from=build /app/vendor/cpp-driver/build/libcassandra.so* /
