# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  cassandra:
    image: cassandra:4.0
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      timeout: 2m

  driver:
    build:
      context: .
      cache_to:
        - "type=gha"
      cache_from:
        - "type=gha"
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
