# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
networks:
  lucas-net:
name: lucas

version: "3.9"
services:
  cassandra1:
    container_name: cassandra1
    hostname: cassandra1
    image: cassandra:4.1
    cpus: 2.0
    mem_limit: "3G"
    env_file:
      - cassandra.env
    volumes:
      - "./integration/cassandra/cassandra1.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 180

  cassandra2:
    container_name: cassandra2
    hostname: cassandra2
    image: cassandra:4.1
    cpus: 2.0
    mem_limit: "3G"
    env_file:
      - cassandra.env
    volumes:
      - "./integration/cassandra/cassandra2.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9044:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      cassandra1:
        condition: service_healthy

  cassandra3:
    container_name: cassandra3
    hostname: cassandra3
    image: cassandra:4.1
    cpus: 2.0
    mem_limit: "3G"
    env_file:
      - cassandra.env
    volumes:
      - "./integration/cassandra/cassandra3.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9045:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      cassandra2:
        condition: service_healthy

  cass_migrations_amd64:
    container_name: cass_migrations_amd64
    hostname: cass_migrations
    image: cass_migrations_amd64:latest
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u18
    entrypoint: ["bash", "/app/scripts/cass_migrations_entrypoint.sh"]
    environment:
       - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
       - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_u18_amd64:
    platform: linux/amd64
    image: lucas18_amd64:latest
    container_name: lucas_u18_amd64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u18
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
       - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
       - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_u20_amd64:
    platform: linux/amd64
    image: lucas20_amd64:latest
    container_name: lucas_u20_amd64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u20
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
       - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
       - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_u22_amd64:
    platform: linux/amd64
    image: lucas22_amd64:latest
    container_name: lucas_u22_amd64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u22
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
       - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
       - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_u18_arm64:
    platform: linux/arm64
    image: lucas18_arm64:latest
    container_name: lucas_u18_arm64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u18
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
      - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
      - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_u20_arm64:
    platform: linux/arm64
    image: lucas20_arm64:latest
    container_name: lucas_u20_arm64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u20
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
      - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
      - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_u22_arm64:
    platform: linux/arm64
    image: lucas22_arm64:latest
    container_name: lucas_u22_arm64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_u22
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
      - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
      - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_alpine317_arm64:
    platform: linux/arm64
    image: lucas_alpine317_arm64:latest
    container_name: lucas_alpine317_arm64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_alpine_317
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
      - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/aarch64-linux-gnu/?.so
      - LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

  driver_alpine317_amd64:
    platform: linux/amd64
    image: lucas_alpine317_amd64:latest
    container_name: lucas_alpine317_amd64
    mem_limit: "1G"
    build:
      context: .
      target: build
      dockerfile: Dockerfile_alpine_317
      args:
        - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
        - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    init: true
    command: sleep infinity
    ulimits:
      core:
        soft: -1
        hard: -1
    env_file:
      - cassandra.env
    environment:
       - LUA_CPATH=/app/build/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/x86_64-linux-gnu/?.so
       - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
    depends_on:
      cassandra3:
        condition: service_healthy

