# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  cassandra:
    image: cassandra:4.1
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    healthcheck:
      test: ["CMD", "cqlsh"]
      timeout: 2m

  driver:
    build:
      context: .
      target: build
    environment:
      CASSANDRA_HOST: cassandra
