# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  cassandra:
    image: cassandra:4.1
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    mem_limit: 4g
    volumes:
      - "./integration/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "cqlsh"]
      timeout: 3m

  driver:
    build:
      context: .
      target: build
    init: true
    ulimits:
      core:
        soft: -1
        hard: -1
    volumes:
      - "./tmp:/tmp"
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_PORT_SSL: 9142
      CASSANDRA_SSL_CERT: |
        -----BEGIN CERTIFICATE-----
        MIIDFTCCAf0CFANvVixeqww81Fg6W3zuPNE+mOfQMA0GCSqGSIb3DQEBCwUAMEcx
        CzAJBgNVBAYTAkNDMREwDwYDVQQKDAhvcmdfbmFtZTEVMBMGA1UECwwMY2x1c3Rl
        cl9uYW1lMQ4wDAYDVQQDDAVDQV9DTjAeFw0yMzAyMDIyMzU5MjVaFw0zMzAxMzAy
        MzU5MjVaMEcxCzAJBgNVBAYTAkNDMREwDwYDVQQKDAhvcmdfbmFtZTEVMBMGA1UE
        CwwMY2x1c3Rlcl9uYW1lMQ4wDAYDVQQDDAVDQV9DTjCCASIwDQYJKoZIhvcNAQEB
        BQADggEPADCCAQoCggEBAMRqZHFkm5a29bi0fEzJkusTf4GzuiVeh0XM82yUJasu
        44lXaopLMG5CGYD8nRkCmkSIdXT8qsnUze3Gnr3dHdt/PJdZAux8jHyUknY96Gb8
        7WeSdweTXDucN7etThuc8HpOFlomP+sz+37nBv/S1h6FciOSHkCDtELITumePs8B
        ofBLLTf7lmWjhZ3KPmxFdXBG/E0FcLo/+qI4JpJWYZY1hH1ch7iNKLj+xfB/TY7Q
        BWvm3ftza6dacS2W4zHtSM2rCWT7qXqNkfLNR/ZXSEYcmuke93GrU8eCzInzHq9A
        mFCuoAnbvNa0aDe5+lJJGJlocsnww7einJJZjZukoUECAwEAATANBgkqhkiG9w0B
        AQsFAAOCAQEAeFc+tRQbIG2gIRPJCTabtUdHd8JQp8FYrt9jQ6vn7XK5w+QDhkuZ
        cY93oXPr+tluDOwIEoD86UB1QXSHpc+gsUZhCEq4E+K/+S9slsHheYP3xwXuFN7G
        beXVNhfg50YosQ14JFBClsnKeMGi2iflrSFFzJdvFakX+LoXWjwi7dmxLc8GFfym
        i6COmGIZXK5E8mw9OriXf5FeM0DBaXF1oJ+SCAve0o3N/cM+KjWzta7GJWOQEpb5
        ce+f3g9JTuaxVczKlFNmHahAfdzZCkSF1CUvwe6vU8YjoYDOVmZPOgpjyRidwgOl
        eNR72vK1v90SqqKt+SzMzhFqA0oyu4mfdA==
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIDDjCCAfYCCQCwoPe/5B765DANBgkqhkiG9w0BAQsFADBHMQswCQYDVQQGEwJD
        QzERMA8GA1UECgwIb3JnX25hbWUxFTATBgNVBAsMDGNsdXN0ZXJfbmFtZTEOMAwG
        A1UEAwwFQ0FfQ04wHhcNMjMwMjAzMDM1MjAxWhcNMjMwMzA1MDM1MjAxWjBLMQsw
        CQYDVQQGEwJDQzERMA8GA1UECgwIb3JnX25hbWUxFTATBgNVBAsMDGNsdXN0ZXJf
        bmFtZTESMBAGA1UEAwwJbm9kZV9uYW1lMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
        MIIBCgKCAQEAvsgFTOuoJb4UO+81glU6PjH+sT1fYnZYBwL4F7jgD6pQiB1nUJWf
        xIH43wUDlXpJLCGt88SpEPVQGakE0vjCDmbLcdCYTCPu/XmBeV7DyrDvChpppmQh
        JyEK6vllLL2Mx0/yaZIYArQvlYIun7+k763OdUde3c8mzLJd6/55BM13rN5kzo/N
        b5SADIX+7JKDMBhPeDT1x5omxwTQoXfwiG9EUzmligspTkYg+MMu2Z1O0RA0wspc
        8bRzOPqzHp8UHn0T6O2HkfZatJayu+Vn8ugmfYByxaca6XMzl+Qwq/sL8J1zc85N
        +JllzxpMom1Bi0hDY2d5a35HhQadP9M6oQIDAQABMA0GCSqGSIb3DQEBCwUAA4IB
        AQBExp520e78YO8bs9RZ9nsAB3GLqE21+e3WvtqGvJvXpG9QsWEL1nhqcFJUTnEP
        C12LXoauTngxRJdZ62dJb3MtBQXO06MOLtgOO3h/pxbvEwqA9BT+8a7rCW2NUG8v
        h2aa/GBRkMnn5QZf0iNuWa/eHZJEhK5FBoJ9Rr84xGQiHpPU05hUeM7k4D5rr77G
        Zt1Nu6rwVyivmxo+jeDioMlky27+1sB/6DzTAQSqpiKAtLHXiEOODmiMj5Gjq936
        +DQuT0Sl9I9XjiU+WglcEd7XsErQRRRCNYyv3wht1I1TDhtOtVGBnehXYSfZdEje
        RUOaI4OSGsCEEjozv5LAJXcN
        -----END CERTIFICATE-----
      CASSANDRA_SSL_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDSW/6J5HEWtiXf
        sSmBvl4VxrM5Bjs43xpuj8e75vCl5HEHNFLYm/A4akljjQyaKVCbMEoOqbqmPTbK
        mmeafkDb1ldqkYKZd0aFJh+BR1z++A9Az1DQz/4EM0rJt5LyKVoowqoXrpgztEVd
        iYt/9vbgcOs0zetlMsQ4PNOHg/DrDafKD1A9uSzTVGHN86pm9KMqtTSunyoiDoGn
        tr91djQzDEyrjAql3S9LxTMd6nfMq5u4X9D+cpNksCrfUrq4ck2xFiCULPhSDF4L
        zOUtvXw1+fZyC2zjtgY+PFUly2djsiGk6WqAprB5t6QQKiXnON2LhKI9EJBhYE1z
        mwYX0PIfAgMBAAECggEBAMcdkPhRJcKLs5njhhhra39NT8QAY/pXJBvXOQZheRRu
        AZcCLhEeuemMod77WhxqUwQyV0c93ZERjFWGhd609wuf/arABVDil/vctCGYvSwS
        /c0o76RX3Gd5bac2fn9+KPtAF+TGvQbj8myxjzwXNmQIPnsDF3f478cTvF4fw+GY
        mVs4Wqq21HFDVi4yY8YToXir1OG/xNjPfgKlukg/7ZD3lQMUUTiFhKQVmLeyfMJ7
        ur+EXeW5UMu5sOrY2ktvZrgzLoHjbTNOae1lbObxjd6Mc+K2GpYo6qF4MRIGAzUn
        zsykQ+W0lrSqpheFrXjDiP//8sHjKEqNO0mkqae6RIECgYEA9a82/kSenA6QZY+i
        MkaZtiL7RzkS0twfeK06fPcPCIZtH2Yjrh/upz/JyIgu5eU80zQq+nATDAiEP0Fp
        Ma7nx9v51z4So6UAffqkKJbm5n7aNaU+qGSvBgGb4TpkTN1Z9JSL+tQwTq5dwPgN
        15eifYD7FzMVaMIq7V9v2dUn0+ECgYEA2zEUy1p7KP8aPLJ+IRdFPudu3Q2I0G7H
        cp1raRImE2Fk8KEwlTBBydAJIWMd9V8l9ykIgKUKZkziTe5HJGiwbCHxbmHOgEKH
        HslUzRQIxW/WPs1Nqnz7hnZoCaNJgFgHlrL4yDe/RG5rP9jD/0gMOnkUzUyQDl4G
        JjOMfkYxhf8CgYEAoqvV7LuAjXGzOBvHWCSY6Bj3aawng4gOKngAbveic5GWNSEK
        5OLtwL2inG1XKA8FnA5BmrqUUfZdoghsX2Igw5sqLNNDwiihT8ih4uIvllRNpRF5
        kEPCA2cTUCi6eo5hXmjw2i6eoaogF4HmoGYdR54cIrtHJKrTg4IabBAPo+ECgYEA
        kiuQ6mtUZmp4XLHLWtXh36kGTXORIS4+4zgHQPJRYes5HR7g/xxHQwXwkMtAVzk0
        YDaE7QUigkYTRFT6LFWEERgxoKKoyu+Sm/03B+usTb3e6dKPUHo4YdrkVkkF4wjR
        RrXjIeHLMx9PdixfyAWL4hKMxLuh9XLONvt5XVwB+pECgYAfofNCsmDRQ70bl2Ft
        Op03xE30ZnVuj+10mg5cgjF1O46rYW4oLlU8blPrzr9kai2NZyMbJ/Zu4V008nmc
        0AGeWFfasDSZ/4xmS+J4naIkICSjNlUSDXnhCPLFJGoEhG4Bm8yI0gjI7WM5Umxn
        KMRsBqQ+wykNXWNhmWnY5ISyBA==
        -----END PRIVATE KEY-----



