# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  cassandra:
    image: cassandra:4.1
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    mem_limit: 4g
    volumes:
      - "./integration/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml"
      - "./integration/cassandra/node-keystore.jks:/opt/cassandra/keystore.jks"
      - "./integration/cassandra/node-truststore.jks:/opt/cassandra/truststore.jks"
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra"]
      timeout: 3m

  driver:
    build:
      context: .
      target: build
    init: true
    ulimits:
      core:
        soft: -1
        hard: -1
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_PORT_SSL: 9142
      CASSANDRA_USER: cassandra
      CASSANDRA_PASS: cassandra
      CASSANDRA_SSL_PASS: cassandra
      CASSANDRA_SSL_CERT: |
        -----BEGIN CERTIFICATE-----
        MIIDfzCCAmegAwIBAgIESnjhpzANBgkqhkiG9w0BAQsFADBvMRAwDgYDVQQGEwdV
        bmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRMwEQYD
        VQQKEwpMb3R1c0ZsYXJlMRAwDgYDVQQLEwdVbmtub3duMRAwDgYDVQQDEwdVbmtu
        b3duMCAXDTIzMDIwNDA2NDIyMloYDzIxMjMwMTExMDY0MjIyWjBvMRAwDgYDVQQG
        EwdVbmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRMw
        EQYDVQQKEwpMb3R1c0ZsYXJlMRAwDgYDVQQLEwdVbmtub3duMRAwDgYDVQQDEwdV
        bmtub3duMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzJfx597CPjbL
        iIc9l4Y8h9KmJzeJyWOngIGvbO5Fmk+n2W7tLsTL3p5uQ+vqARzd+hBO1ZTBFvkl
        Tp6n+cDTvc0sTEY9mQK7djcl7tRkgxIR5cEN9djMx4NtD7pvZ5o/3iVvFXnvLFXu
        Za/TGCngYqTXSdrpvq6b+dEX9xOkmwQgQH0wL53yFx1EOdC+9L//h4jDts/xNmdr
        5UzYpMBBY8XVSPSX+3k2OZzmi+6bAAdw6hQLWiHud9rvNEoYhhEdgQcIGIiYYHC8
        t/6xwq24QHjGi2K5Fahic60yDqwCgEErBYPQuqiNrAKSvGf2sBqOktws7GMQ/9N2
        p9hv5gbrnwIDAQABoyEwHzAdBgNVHQ4EFgQUkzEoR4oKFRd1mY0X55SairebRZEw
        DQYJKoZIhvcNAQELBQADggEBALnlSDHj9Wgzgt9VIptmpWeWy8j4sFCaCMCI7HKQ
        kCAW+wtyYDxYoBqXX7nhDwS7/fVAf9Ww4xlEgKIxQjuxP2401QDsjNCc/quCAJN8
        AmUMFXIk0xeJEPhLC5pIrEehsQ2jDo/LIKW1EKMpW81Z5oXwiSdlocu6hPTWw+Ht
        KdgKSOWRoEwpknW+DPei13u55ZW/w5FljDmHSt+9hw92W1l/fdmKcJtP715Dy2ur
        BPg3VMPxsjbVNSBw4b5OnBeMiUFiFatDiMIiaHeZFb8PZ/5Zs32hVuDJUkyKZqg7
        UtuTR5x4Uo0pXGgKlFb6te2PdbSX+uiS4kevCaPSjz4RAVw=
        -----END CERTIFICATE-----
      CASSANDRA_SSL_KEY: |
        -----BEGIN ENCRYPTED PRIVATE KEY-----
        MIIFDjBABgkqhkiG9w0BBQ0wMzAbBgkqhkiG9w0BBQwwDgQI06dbFk2QZbwCAggA
        MBQGCCqGSIb3DQMHBAhGF9D06u0s/wSCBMjmtZww6zukEA/DbO7HlCHlA4bpt3GW
        yrWwWSyTdlXePjjUM+WoIkMIlxUuJKT7xQV4AQWeOm1E3jtOv/kaYx7fH19eL+/5
        HZIHiuCCmiHQArIkipqWY46saDrl1Cm0vuvJo9Bq5MJLJ3e7EteQm/3k+D9nMRAC
        zPlzLJOnCrUphurEraW/YKFj1AmK7GZXMDfd291MWMWLfJxXVt6wE1M4Fgft7qAN
        p8yzO6GjzY2/5KB3aeW6KPioll0psZD6mwUMiVJXdMb+4d1PrgobrFwWwGUp5rGF
        eeOXV8v8EwJpEoB9zk9uJDZfZI/UvLbuFYAXVje7FA/op56A5SasWHT6HoOtLWIw
        5buF70lToi7t1TaZmbNRivajn4OWOCN2gYoM3cA93AaXlhHXld1G8b61fEL1WZCh
        IutaJQkkaxjaKzIbKZiiWZ2IYGvqOuJu7hx5tsq9RhvauDJNwSpn97YvZ3ikPRH+
        uGITCK30a6pNsVl+eu+jaWAZeU3TnsaC5G382xmeuN0Y0V/JRzByV/YFjkjc0A5d
        IussVuXzYoVGAvA2ExiR59zKDqPGI2P3JkVly+ktSZo84HCsBnVYmzPyu9SS3RzN
        payHIn3zcE/XB+g53/Q4igyKnyu+Nsxulw9jAN44LXqWj5VG/R9wbenY8/WZG1aS
        WJS31TZkzppO6If5SRd+ggnQvg7XGRLSfhqtNHnuwxUyZTKXScAElA4DMc/z7qiw
        I9sXc6Cf0OWAjtIvLQVzQjuIwaxrPSRh0rJl89jwO4k/wm1flBI6KXvATA4UYRIh
        8OMNFY6k0sCsLZ4bJ17JFOcqpee2GjCoUMnDwAvcWLmmFH0HfAlr3b/l9248ZBd5
        QWrE3cAZ2lT7Z0M7480rv7OgoMf6XTvyOIrT6D+FM0cXwhdFzuPGu9uQD8Qjetz6
        bIYYBTkH9PduwkaFM5DM8XGRkClUuySH85ZcbZixCsjLJebOKSLLH0bB+wOq/A5u
        2Dlp3kW8RpZ26uUTqdL/SMNIattb+LB0U+HF1laRjsRzhFEMnz8/mdP6Ywc5wOsY
        AFjIfRnbt0mai7bg1Jbqq479mLUrQxy5GLLMz1LR93XkgrDOtAPAK26wVdtPW6Bl
        OclsYxYy0H/+pAbhf2Rvl5Ny5OLfCIoahRO7j4XUadVTNSHaCeu1Eyv9fK7PGxUY
        nEHk01cSqq83i9eBXRVKy9Kx0w+VFqgMHIGmMFh6j4iLo7Vd84n1BpQ9vtUhVnXr
        u12tBsmUgUy2EcSpxfIg3Wu+Y+FRqXgYTwQiLpodkZPAibwkDIPG6CX6YxCE2sPR
        Rju6nrAEe09Z5v/5J1C0p8cMBU+ehRQ1w4FHGD9HrFMnvxROKj/SsyQPsxG49H0d
        3SOfMWdlvSPOFLz9G4KBo8IFNgtxIB3cZbpPvhAqSA19vZ750IBVqMPueUOIiD5q
        lP6IH0UEfWVfbx6wrTvl2gGWecspSUGHA2te2CVA/0VGSrGHnjXdcnNLmkG2lKuc
        FdoeyPjfC/o5zxuoDSif8isHnzyzmTfvlQyXEdzqRffmL+Dgv1R3mSIZQLVVCuho
        DYCtYlGfT85xZFI/ECSJBp9KumjCLxsUECGSDwSYwgj8t3PRA6HRKmhIb3tvFHSz
        Ckk=
        -----END ENCRYPTED PRIVATE KEY-----
