name: lucas

services:
  cassandra:
    image: cassandra:4.0
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      timeout: 2m

  driver:
    build:
      context: ..
    network_mode: host

