name: lucas

services:
  cassandra:
    image: cassandra:4.0
    environment:
      CASSANDRA_LISTEN_ADDRESS: cassandra
    ports:
      - "9042:9042"
    volumes:
      - "./init.cql:/init.cql:ro"
    healthcheck:
      test: "[ $$(nodetool -h ::FFFF:127.0.0.1 statusgossip) = running ]"

  driver:
    build:
      context: ..
    network_mode: host

