# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on: [push]

name: build
jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: apt install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq boxes

      - uses: docker/metadata-action@v4
        id: meta
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: ghcr.io/lotusflare/lucas
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}

      - uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: build
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Integration tests
        run: |
          echo '/tmp/core-%e.%p.%t' | sudo tee /proc/sys/kernel/core_pattern
          ./start.sh -bt

      - name: Debug
        if: ${{ failure() }}
        run: |
          sudo chown -R $USER:$USER ./tmp
          docker inspect $(docker compose ps -qa driver)

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: integration-tests-dump
          path: ./tmp
