# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on: [push]

name: build
jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: apt install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq boxes

      - uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: build
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha

      - name: Integration tests
        run: |
          echo '/tmp/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
          ./start.sh -bt

      - name: Debug
        if: ${{ failure() }}
        run: docker inspect $(docker compose ps -qa driver)

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: dump
          path: ./tmp
