# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on: [push]

name: build
jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: apt install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq boxes

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: ghcr.io/lotusflare/lucas
          tags: |
            type=semver,pattern={{version}}

      - uses: docker/build-push-action@v4
        with:
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: artifacts
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Integration tests
        run: |
          ./start.sh -bt

      - name: Debug
        if: ${{ failure() }}
        run: |
          docker inspect $(docker compose ps -qa driver)
          docker compose cp driver:/app/core ./core
          sudo chown -R $USER:$USER ./core

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: integration-tests-dump
          path: ./core
