name: Build

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bring up environment
        working-directory: integration
        run: |
          docker compose build
          docker compose up cassandra --wait
          cat init.cql | docker compose exec -T cassandra cqlsh

      - name: Integration tests
        working-directory: integration
        run: |
          docker compose run driver busted --output=TAP .
