name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: docker/setup-buildx-action@v2

      - name: apt install
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq boxes

      - uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          dockerfile: Dockerfile
          cache-from: type=gha
          cache-to: type=gha

      - name: Integration tests
        run: ./start.sh -bt
