name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: docker/setup-buildx-action@v2

      # - uses: docker/build-push-action@v3
      #   with:
      #     push: false
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Bring up environment
        working-directory: integration
        run: |
          docker compose up cassandra --wait
          cat init.cql | docker compose exec -T cassandra cqlsh

      - name: Integration tests
        working-directory: integration
        run: |
          docker compose exec driver busted --output=TAP .
