# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on: [push]

name: ci
jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
      COMPOSE_DOCKER_CLI_BUILD: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: apt install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq boxes

      - uses: docker/metadata-action@v4
        id: meta
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: ghcr.io/lotusflare/lucas
          tags: |
            type=semver,pattern={{version}}

      - uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          context: .
          target: artifacts
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha

      - name: Integration tests
        run: |
          ./start.sh -bt
