name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bring up environment
        run: |
          docker compose build
          docker compose up cassandra --wait
          cat integration/init.cql | docker compose exec -T cassandra cqlsh

      - name: Integration tests
        run: |
          docker compose run driver busted --output=TAP .
