on:
  push:
    branches: [master]

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: lucas

      - name: Build artifact
        run: |
          docker compose build driver
          docker compose create driver
          docker compose cp driver:/app/build lucas.so

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        if: steps.release.outputs.release_created
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: lucas.so
